steps:
  # Step 1: SSH into the remote VM
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'new-instance'  # Replace with your VM instance name
      - '--zone'
      - 'asia-south1-a'  # Replace with your VM's zone
      - '--project'
      - 'jmc-devsecops'  # Replace with your GCP project ID
      - '--command'
      - 'hostname'
      steps: