steps:
  # Step 1: SSH into the remote VM and execute commands
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - '--zone'  # Argument order corrected
      - 'asia-south1-a'  # Replace with your VM's zone
      - '--project'
      - 'jmc-devsecops'  # Replace with your GCP project ID
      - 'new-instance'  # Replace with your VM instance name
      - '--'  # Separates gcloud args from commands to execute on the VM
      - 'hostname'  # Your intended commands to run on the VM
      - '&&'  # Separate subsequent commands if needed
      - 'other-command-1'  # Add more commands as needed
      - 'other-command-2'

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'  # Use the official Docker builder
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-image:latest', '.']

# Push the image to Container Registry (if required)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['docker', 'push', 'gcr.io/$PROJECT_ID/my-image:latest']

# Deploy to your preferred service (e.g., Cloud Run)
  - name: 'your-deployment-step'  # Customize for your deployment method
    args: ['...']  # Replace with your deployment commands
